### ISSUE TITLE
Provide Apk Also

### ISSUE THREAD

**Issue by eagleanurag** [TrifiAmanallah/Android-Line-Follower-Robot#1]
Please Provide an apk file so that people who don,t know to make an app with source code will get help from that please do that

**Comment by TrifiAmanallah** [comment]
File added.

**Comment by eagleanurag** [comment]
thankyou soo much my Friend

if you use facebook I would like to connect to people like you

Send me request at https://www.facebook.com/eagleanurag

sorry for this commit
